### ISSUE TITLE
Cannot assign to read only property 'exports' of object

### ISSUE THREAD

**Issue by bdrtsky** [035media/tailwindcss-flexbox-order#1]
This is what I have with plugin using Nuxt

```
app.js:411 Error: [nuxt] Error while mounting app: TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

**Comment by adevade** [comment]
Hey @bdrtsky! Thanks for reporting your issue! 

Could you please include a little more information about the problem? I've never used Nuxt myself, so I don't know what could be causing this. 

Also, which version of Tailwind are you using? I haven't updated this plugin to be compatible with 1.x yet. I plan on doing that as soon as it's out of beta. Should be in the following week or two. 

Kind regards
