### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by opdavies** [035media/tailwindcss-flexbox-order#2]
Going to work on this in https://github.com/opdavies/tailwindcss-flexbox-order.

**Comment by adevade** [comment]
We'll gladly accept a pull request! 
And if you need/want any help I'm happy to help!

**Comment by opdavies** [comment]
I've added some tests in https://github.com/035media/tailwindcss-flexbox-order/pull/3. Let me know if you can think of any other scenarios that you think would be good to test.
